// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTc5WFvzaByG4mSN__SvRoXkSNuJZSDrE',
    appId: '1:512161913460:web:ede2fd394a51ccd5434f21',
    messagingSenderId: '512161913460',
    projectId: 'profburo-255e8',
    authDomain: 'profburo-255e8.firebaseapp.com',
    storageBucket: 'profburo-255e8.firebasestorage.app',
    measurementId: 'G-13993EBPBN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3QE7-I6e8PYiMDX6_JBitEnhl0piyuEc',
    appId: '1:512161913460:android:1fc61f1af8a37099434f21',
    messagingSenderId: '512161913460',
    projectId: 'profburo-255e8',
    storageBucket: 'profburo-255e8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5s_GClmYB2uGFWNlGF53Og2Ww3QNKJAs',
    appId: '1:512161913460:ios:435f73817061c17c434f21',
    messagingSenderId: '512161913460',
    projectId: 'profburo-255e8',
    storageBucket: 'profburo-255e8.firebasestorage.app',
    iosBundleId: 'com.example.aidApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5s_GClmYB2uGFWNlGF53Og2Ww3QNKJAs',
    appId: '1:512161913460:ios:435f73817061c17c434f21',
    messagingSenderId: '512161913460',
    projectId: 'profburo-255e8',
    storageBucket: 'profburo-255e8.firebasestorage.app',
    iosBundleId: 'com.example.aidApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTc5WFvzaByG4mSN__SvRoXkSNuJZSDrE',
    appId: '1:512161913460:web:af9960294c9b1f5a434f21',
    messagingSenderId: '512161913460',
    projectId: 'profburo-255e8',
    authDomain: 'profburo-255e8.firebaseapp.com',
    storageBucket: 'profburo-255e8.firebasestorage.app',
    measurementId: 'G-129TZH0SHJ',
  );
}
